"""Single source of truth for services, FAQ, recommender keywords and UI strings.

Arabic is written in consistent formal Arabic (MSA). Client-supplied copy (Home / About lists)
lives in build.py and is used verbatim. Everything marked DRAFT in README needs client approval.
"""

SERVICES = [
    # ---- Indian massages -------------------------------------------------
    dict(id="shirodhara", cat="indian", latin="Shirodhara", ar="جلسة الشيرودهارا", img="st-shirodhara",
         dur=[(60, 26), (90, 30)],
         short=("تدفّق هادئ من الزيت الدافئ على الجبهة لتهدئة الأعصاب وتحسين النوم.",
                "A continuous stream of warm oil poured on the forehead to calm the nervous system and improve sleep."),
         what=("تستلقين براحة بينما يُسكب زيت دافئ بانسياب مستمر وبطيء على الجبهة من وعاء خاص طوال الجلسة.",
               "You lie back comfortably while warm oil is poured in a slow, continuous stream onto your forehead from a special vessel throughout the session."),
         benefit=("تهدئة عميقة للجهاز العصبي وتحسين جودة النوم.",
                  "Deep calming of the nervous system and improved sleep quality.")),
    dict(id="kativasti", cat="indian", latin="Kati Vasti", ar="كاتي فاستي", img=None,
         dur=[(60, 23), (90, 26)],
         short=("كمادات عشبية دافئة لتخفيف آلام الظهر وإرخاء العضلات.",
                "Herbal poultices to relieve back pain and relax the muscles."),
         what=("يوضع حاجز صغير من العجين حول أسفل الظهر، ثم يُملأ بزيت عشبي دافئ يستقر على المنطقة لبعض الوقت.",
               "A small dam of dough is placed around the lower back and filled with warm herbal oil that rests on the area for a while."),
         benefit=("تخفيف الشعور بآلام أسفل الظهر.", "Relief from lower back discomfort.")),
    dict(id="faceneck", cat="indian", latin="Face & Neck", ar="تدليك الوجه والرقبة", img="real-face",
         dur=[(60, 12)],
         short=("تدليك للوجه والرقبة بزيت الزعفران وخلاصة اللوتس.",
                "Face and neck massage with saffron oil and lotus flower extract."),
         what=("تدليك لطيف بحركات دائرية للوجه والرقبة بزيت الزعفران وخلاصة زهرة اللوتس.",
               "A gentle circular massage of the face and neck using saffron oil and lotus flower extract."),
         benefit=("تنشيط الدورة الدموية في الوجه ومنح البشرة إشراقة.",
                  "Boosted facial circulation and an instant glow.")),
    dict(id="abhyanga", cat="indian", latin="Abhyanga", ar="مساج الأبيانغا", img="st-oil-pour",
         dur=[(60, 25), (90, 29)],
         short=("مساج هندي بالزيوت الدافئة يمنح الجسم إحساسًا بالراحة والاسترخاء.",
                "A warm-oil Indian massage that gives the body a feeling of comfort and relaxation."),
         what=("تدليك بزيت دافئ بحركات طويلة ومتناغمة لكامل الجسم بضغط متوسط.",
               "A warm-oil massage with long, synchronized strokes over the full body at medium pressure."),
         benefit=("تجديد الطاقة وتخفيف الإرهاق العام.", "Renewed energy and reduced overall fatigue.")),
    dict(id="kizhi", cat="indian", latin="Kizhi", ar="مساج الكيزهي", img="real-kizhi-neck",
         dur=[(60, 23), (90, 27)],
         short=("كمادات عشبية دافئة تُمرَّر على الجسم بإيقاع منتظم لتمنحك راحة عميقة.",
                "Warm herbal compresses pressed rhythmically over the body for deep comfort."),
         what=("تُمرَّر على الجسم كمادات قماشية دافئة محشوّة بأعشاب طبيعية بضغط منتظم.",
               "Warm cloth pouches filled with natural herbs are pressed rhythmically over the body."),
         benefit=("الراحة للعضلات والمفاصل المتعبة.", "Comfort for tired muscles and joints.")),
    dict(id="nasiyam", cat="indian", latin="Nasiyam", ar="ناسيام", img=None,
         dur=[(30, 10)],
         short=("تدليك للوجه مع بخار وقطرات عشبية لراحة الأنف في مواسم الحساسية.",
                "Facial massage with steam and herbal drops for seasonal comfort."),
         what=("تستنشقين بخارًا عشبيًا، ثم تُوضع قطرات من زيت عشبي في الأنف.",
               "You inhale herbal steam, then herbal oil drops are administered through the nose."),
         benefit=("تخفيف احتقان الجيوب الأنفية وأعراض الحساسية الموسمية.",
                  "Relief from sinus congestion and seasonal allergies.")),
    dict(id="headscrub", cat="indian", latin="Indian Head Scrub & Massage", ar="تقشير وتدليك فروة الرأس", img=None,
         dur=[(60, 18), (90, 20)],
         short=("تقشير لفروة الرأس وتدليك بالزيت لتغذية الشعر.",
                "Scalp exfoliation and oil massage to nourish the hair."),
         what=("تقشير لطيف لفروة الرأس يعقبه تدليك بالزيت لتغذية الشعر من الجذور.",
               "A gentle scalp exfoliation followed by an oil massage that nourishes hair from the roots."),
         benefit=("فروة رأس أكثر صحة وتقليل تساقط الشعر.", "Healthier scalp and reduced hair fall.")),
    dict(id="holistic", cat="indian", latin="Holistic Package", ar="الباقة المتكاملة", img="real-tray",
         dur=[(90, 40)],
         short=("تدليك كامل الجسم + كمادات دافئة + شيرودهارا.",
                "Full body massage + warm compresses + Shirodhara."),
         what=("رحلة متكاملة: تدليك كامل للجسم وكمادات دافئة، وتُختتم بجلسة شيرودهارا.",
               "A complete journey: full body massage, warm compresses, finishing with a Shirodhara session."),
         benefit=("تجربة استرخاء شاملة من اللحظة الأولى إلى الأخيرة.",
                  "A complete relaxation experience from start to finish.")),
    # ---- International massages -----------------------------------------
    dict(id="hotstone", cat="other", latin="Hot Stone Massage", ar="مساج الأحجار الساخنة", img="st-stones",
         dur=[(60, 18), (90, 22)],
         short=("تدليك بالأحجار الساخنة للاسترخاء العميق.", "Hot stone massage for deep relaxation."),
         what=("تُستخدم أحجار ناعمة دافئة كأداة تدليك على العضلات المشدودة.",
               "Smooth heated stones are used as a massage tool over tense muscles."),
         benefit=("استرخاء عميق وسريع للعضلات المتيبسة.", "Fast, deep relaxation for stiff muscles.")),
    dict(id="relaxation", cat="other", latin="Relaxation Massage", ar="مساج الاسترخاء", img=None,
         dur=[(60, 16), (90, 20)],
         short=("تدليك استرخائي لكامل الجسم بزيت عطري.", "Full body relaxation massage with aromatic oil."),
         what=("تدليك خفيف ومتوازن لكامل الجسم بزيت عطري مهدّئ.",
               "A light, even, full-body massage with soothing aromatic oil."),
         benefit=("هدوء عام وتخفيف التوتر.", "General calm and reduced stress.")),
    dict(id="reflexology", cat="other", latin="Reflexology", ar="تدليك القدمين", img="real-footbath",
         dur=[(60, 10)],
         short=("تدليك للقدمين لتنشيط الدورة الدموية.", "Foot massage to stimulate blood circulation."),
         what=("ضغط بأصابع مدرَّبة على نقاط محددة في باطن القدم.",
               "Trained finger pressure applied to specific points on the sole of the foot."),
         benefit=("تنشيط الدورة الدموية وتخفيف تعب الوقوف الطويل.",
                  "Better circulation and relief from long hours on your feet.")),
    dict(id="headshoulder", cat="other", latin="Head & Shoulder Massage", ar="مساج الرأس والكتفين", img=None,
         dur=[(60, 13), (90, 17)],
         short=("تدليك للرأس والكتفين لتحسين الدورة الدموية.",
                "Head and shoulder massage to improve circulation."),
         what=("تدليك مركّز على فروة الرأس والرقبة والكتفين.",
               "A focused massage over the scalp, neck, and shoulders."),
         benefit=("تخفيف شدّ العضلات الناتج عن الجلوس الطويل أمام الشاشات.",
                  "Relief from muscle tension caused by long hours sitting.")),
    dict(id="bamboo", cat="other", latin="Bamboo Massage", ar="مساج الخيزران", img=None,
         dur=[(60, 18), (90, 22)],
         short=("تدليك بعصي الخيزران الدافئة للوصول إلى العضلات الأعمق.",
                "Warm bamboo stick massage for deeper muscles."),
         what=("تُمرَّر عصي خيزران دافئة على العضلات بضغط يزداد تدريجيًا.",
               "Warm bamboo sticks are rolled over the muscles with gradually increasing pressure."),
         benefit=("الوصول إلى طبقات عضلية أعمق مقارنةً باليد وحدها.",
                  "Reaches deeper muscle layers more effectively than hands alone.")),
    dict(id="deeptissue", cat="other", latin="Deep Tissue Massage", ar="مساج الأنسجة العميقة", img=None,
         dur=[(60, 18), (90, 22)],
         short=("تدليك بضغط قوي لتخفيف توتر العضلات.", "Firm pressure massage to relieve muscle tension."),
         what=("ضغط قوي ومركّز على طبقات العضلات العميقة والنقاط المشدودة.",
               "Firm, focused pressure on deep muscle layers and tight spots."),
         benefit=("تخفيف الشدّ العضلي والمناطق المتيبسة.", "Relief from muscle tension and stiff areas.")),
    dict(id="thai", cat="other", latin="Thai Massage", ar="مساج التاي", img=None,
         dur=[(60, 15)],
         short=("تمارين إطالة لكامل الجسم لتحسين المرونة.",
                "Full body stretching techniques to improve flexibility."),
         what=("حركات إطالة ومدّ لطيفة لكامل الجسم، أشبه باليوغا السلبية.",
               "Gentle full-body stretching movements, similar to passive yoga."),
         benefit=("تحسين مرونة الجسم والمفاصل.", "Improved body and joint flexibility.")),
    dict(id="shiatsu", cat="other", latin="Shiatsu", ar="شياتسو", img=None,
         dur=[(60, 18), (90, 22)],
         short=("تدليك على نقاط ضغط محددة لتخفيف التوتر.", "Pressure-point massage to reduce tension."),
         what=("ضغط بأصابع اليد على نقاط طاقة محددة في الجسم.",
               "Finger pressure applied to specific energy points across the body."),
         benefit=("تخفيف التوتر العام وتحقيق التوازن.", "Reduced overall tension and balanced energy.")),
]

FAQ = [
    (("كم دقيقة قبل الموعد يُفضَّل أن أصل؟", "How early should I arrive before my appointment?"),
     ("نوصيكِ بالوصول قبل موعدك بـ 10–15 دقيقة، لتأخذي وقتك وترتاحي قليلًا قبل بدء الجلسة.",
      "We recommend arriving 10-15 minutes early, so you can settle in and relax a little before your session begins.")),
    (("هل يجب أن أتناول الطعام قبل الجلسة؟", "Should I eat before my session?"),
     ("الأفضل تناول وجبة خفيفة قبل الجلسة بساعتين على الأقل؛ فالجلسة تكون أكثر راحة حين لا تكون المعدة ثقيلة ولا فارغة تمامًا.",
      "It's best to have a light meal at least two hours before your session, for maximum comfort during the treatment.")),
    (("هل يمكنني إلغاء الحجز أو تأجيله؟", "Can I cancel or reschedule my booking?"),
     ("بالتأكيد، يمكنك الإلغاء أو التأجيل؛ نرجو إبلاغنا قبل الموعد بـ 24 ساعة على الأقل لنتمكن من إتاحته لضيفة أخرى.",
      "Yes, you can cancel or reschedule — please let us know at least 24 hours in advance so we can offer the slot to another guest.")),
    (("ماذا أرتدي للجلسة؟", "What should I wear to my session?"),
     ("نوفّر لكِ ملابس مريحة مخصصة للجلسة، فلا داعي لإحضار أي شيء.",
      "We provide comfortable session attire for you, so there's no need to bring anything.")),
    (("هل الجلسات مناسبة أثناء الحمل؟", "Are sessions safe during pregnancy?"),
     ("بعض الجلسات غير مناسبة أثناء الحمل. تواصلي معنا قبل الحجز لنساعدك في اختيار الأنسب لحالتك.",
      "Some treatments aren't suitable during pregnancy. Please contact us before booking so we can help you choose what's best for you.")),
    (("هل يمكنني الحجز لأكثر من شخص في الموعد نفسه؟", "Can I book for more than one person at the same time?"),
     ("حاليًا يكون كل حجز عبر الموقع لشخص واحد. إن رغبتِ بالحجز مع صديقتك في الوقت نفسه، راسلينا عبر واتساب وسنرتّب ذلك لكما.",
      "Each online booking is currently for one person. If you'd like to book alongside a friend at the same time, message us on WhatsApp and we'll arrange it.")),
]

# keyword -> service scoring for the "tell us how you feel" recommender (from the current site)
SYMPTOMS = {
    "shirodhara": "نوم ، ارق ، أرق ، توتر ، اعصاب ، أعصاب ، قلق ، صداع ، تركيز ، ذهني ، تفكير ، مخي ، sleep ، insomnia ، anxiety ، stress ، headache ، focus",
    "kativasti": "ظهر ، فقرات ، ديسك ، النسا ، فقرة ، back ، spine ، sciatica",
    "faceneck": "وجه ، بشرة ، رقبة ، تجاعيد ، نضارة ، face ، skin ، neck",
    "abhyanga": "اجهاد ، إجهاد ، تعب ، ارهاق ، إرهاق ، استرخاء ، طاقة ، خمول ، tired ، fatigue ، exhausted ، energy ، relax",
    "kizhi": "مفاصل ، تيبس ، رياضة ، عضلات متيبسة ، التهاب ، joint ، stiff ، sport ، inflammation",
    "nasiyam": "حساسية ، زكام ، جيوب انفية ، جيوب أنفية ، احتقان ، انف ، أنف ، allergy ، sinus ، congestion",
    "headscrub": "شعر ، فروة ، تساقط ، قشرة ، جفاف الشعر ، hair ، scalp ، dandruff",
    "holistic": "شامل ، كل حاجة ، كل شيء ، تجربة كاملة ، دلع ، full ، complete ، everything",
    "hotstone": "برد ، برود ، عضل عميق ، تصلب ، شتاء ، cold ، deep muscle ، winter",
    "relaxation": "استرخاء ، هدوء ، راحة ، ضغط نفسي ، قلق خفيف ، سترس ، relax ، calm ، stress",
    "reflexology": "قدم ، قدمين ، رجل ، وقفة ، تورم ، دوالي ، مشي كتير ، feet ، foot ، standing ، swelling",
    "headshoulder": "كتف ، رقبة ، جلوس ، كمبيوتر ، لابتوب ، موبايل ، شد عضلي ، shoulder ، neck ، desk ، computer ، laptop ، sitting",
    "bamboo": "شد عضلي ، تيبس عميق ، عضلات كبيرة ، deep tension ، large muscles",
    "deeptissue": "الم مزمن ، ألم مزمن ، شد قوي ، رياضي ، عضلات متيبسة جدا ، chronic pain ، athlete ، deep tissue",
    "thai": "مرونة ، تيبس المفاصل ، اطالة ، إطالة ، جسم متيبس ، flexibility ، stretch ، stiff body",
    "shiatsu": "نقاط ضغط ، توتر عام ، صداع نصفي ، ضغط عصبي ، pressure points ، migraine ، general tension",
}

# UI strings used by JS renderers: key -> (ar, en)
STR = {
    "from": ("من", "From"),
    "kwd": ("د.ك", "KWD"),
    "minutes": ("دقيقة", "min"),
    "bookBtn": ("احجزي", "Book"),
    "discover": ("اكتشفي الجلسة", "Discover"),
    "recBadge": ("الأنسب لكِ", "Best match for you"),
    "recFallback": ("لم نعثر على تطابق دقيق، لكن «مساج الاسترخاء» يناسب معظم الضيفات، أو تصفّحي كل الخدمات أدناه.",
                    "We couldn't find an exact match, but Relaxation Massage usually works well — or browse all services below."),
    "recShort": ("اكتبي ما تشعرين به بثلاثة أحرف على الأقل.", "Please describe how you feel (3+ characters)."),
    "noSlots": ("لا توجد مواعيد متاحة في هذا اليوم، جرّبي تاريخًا آخر.", "No slots available on this day, try another date."),
    "slotNote": ("الأوقات المشطوبة محجوزة مسبقًا.", "Strikethrough times are already booked."),
    "slotsLoading": ("جارٍ تحميل المواعيد…", "Loading available times…"),
    "slotsError": ("تعذّر تحميل المواعيد. تحقّقي من الاتصال وحاولي مجددًا.", "Couldn't load times. Check your connection and try again."),
    "basedOn": ("بناءً على", "Based on"),
    "reviewSingular": ("رأي", "review"),
    "reviewPlural": ("آراء", "reviews"),
    "reviewsEmpty": ("لا توجد آراء بعد — كوني أول من يشارك تجربتها.", "No reviews yet — be the first to share your experience."),
    "conflictAlert": ("عذرًا، تم حجز هذا الموعد للتو. الرجاء اختيار وقت آخر.", "Sorry, this slot was just booked. Please choose another time."),
    "connError": ("حدث خطأ في الاتصال، حاولي مرة أخرى.", "A connection error occurred, please try again."),
    "receiptService": ("الخدمة", "Service"), "receiptDuration": ("المدة", "Duration"),
    "receiptDate": ("التاريخ", "Date"), "receiptTime": ("الوقت", "Time"),
    "receiptPrice": ("السعر", "Price"), "receiptName": ("الاسم", "Name"),
    "am": ("ص", "AM"), "pm": ("م", "PM"),
    "indianCat": ("مساجات هندية", "Indian Massages"), "otherCat": ("مساجات عالمية", "International Massages"),
    "detailsLabel": ("التفاصيل", "Details"), "whatHappensLabel": ("ماذا يحدث في الجلسة", "What happens"),
    "benefitLabel": ("الفائدة الرئيسية", "Main benefit"),
    "chooseDuration": ("المدة", "Duration"),
    "sending": ("جارٍ الإرسال…", "Sending…"),
    "reviewThanks": ("شكرًا لك! سيظهر رأيك بعد مراجعته من فريقنا.", "Thank you! Your review will appear after a quick review by our team."),
    "reviewInvalid": ("الرجاء اختيار التقييم وكتابة الاسم والرأي.", "Please choose a rating and fill in your name and review."),
    "complaintThanks": ("تم إرسال شكواك — شكرًا لإخبارنا.", "Your complaint has been sent — thank you for letting us know."),
    "complaintInvalid": ("الرجاء تعبئة الاسم ورقم واتساب ونص الشكوى.", "Please fill in your name, WhatsApp number and complaint."),
    "demoNote": ("وضع تجريبي: لم يُرسل أي شيء إلى النظام.", "Demo mode: nothing was sent to the system."),
    "monthNames": (["يناير","فبراير","مارس","أبريل","مايو","يونيو","يوليو","أغسطس","سبتمبر","أكتوبر","نوفمبر","ديسمبر"],
                   ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]),
}
